### ISSUE TITLE
Create official docker image

### ISSUE THREAD

**Issue by f3l1x** [nette/web-project#13]
I'm running many application in Docker environment. We could prepare some official/non-official docker container for nette/web-project or nette/sandbox. 

Just for education reasons and also for easy-to-run/easy-to-test.

What do you think @dg @chemix @milo?

**Comment by dg** [comment]
I have no idea what is Docker.

**Comment by f3l1x** [comment]
The best thing is to look at their website - https://www.docker.com/what-docker.

Docker is great tool for developing and automatization (isolation, security, scaling, etc..). Only thing you have to do is to make a recipe (`Dockerfile`) how your environment should looks like and thats all.

```Dockerfile
FROM debian:sid

MAINTAINER Milan Felix Sulc <rkfelix@gmail.com>

RUN apt-get update && \
	apt-get upgrade -y && \
	apt-get install -y \
		curl \
		git \
		php7.0-cli \
		php7.0-mbstring \
		php7.0-intl \
		php7.0-json \
		php7.0-gd \
		php7.0-xml \
		php7.0-sqlite3 \
		php7.0-zip \
		php7.0-tokenizer && \
	curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
	cd /srv && \
	composer create-project nette/sandbox /srv && \
	apt-get remove -y curl git && \
	apt-get clean -y && apt-get autoclean -y && apt-get autoremove -y && \
	rm -rf /var/lib/apt/lists/* /var/lib/log/* /tmp/* /var/tmp/*

WORKDIR /srv

CMD php -S 0.0.0.0:80 -t /srv/www
```
For example. You can download this recipe and bake it (`build it in docker language`) to a final environment. You don't have to worry about PHP version, apache or nginx, all extensions. 

There are many developers at these days who have all projects in Docker to make things (developing) faster and easier. 

I could prepare these Docker files for nette if you like.

**Comment by dg** [comment]
If you think it is useful, it will be good.

**Comment by chemix** [comment]
I'm docker newbie

**Comment by foxycode** [comment]
@f3l1x Do you know Nanobox? Not quite docker, but it uses it and it's really great or development.

https://github.com/sunfoxcz/nanobox-nette

**Comment by f3l1x** [comment]
There are some tryouts.

1. planette/dockerfiles (https://github.com/planette/dockerfiles)

```
docker run -it --rm -p 8000:80 planette/nette-sandbox
```

2. planette/playground (https://github.com/planette/playground)

- https://planette-nette-tracy.now.sh/
- https://planette-nette-checker.now.sh/

----

Closing it for now. Let me known if someone needs help.
