### ISSUE TITLE
Make `RouterFactory::createRouter` as non static call

### ISSUE THREAD

**Issue by newPOPE** [nette/web-project#2]
In my opinion is better access for beginners (first look to config file) that one service use another. So my recommendation is rewrite routing to dynamic. And they can inject some another things to `RouterFactory` if it will be dynamic. PR?

**Comment by klimesf** [comment]
You can inject dependencies via typehinted parameters of the method.
For example `public static function createRouter(Nette\Database\Context $database)` will automagically inject the database context.

**Comment by newPOPE** [comment]
Okay, nevermind. I don't like static functions like this but maybe for example of functionality is good. I don't know.

**Comment by dg** [comment]
Static functions are fine ;)

**Comment by Majkl578** [comment]
Yeah changing function signature and fixing its usage every time you change dependency, so cool.

**Comment by dg** [comment]
Yeah changing constructor signature and fix its usage and adding new properties every time you change dependency, so cool.

**Comment by Majkl578** [comment]
My point was a bit more related to factories in general, that you hide constructor's parameters behind an instance once and then just use the factory method via instance.
I can imagine some code or test like:

``` php
$foo = new Something($a, $b, $c); // oops, we need $d
$all['a'] = $foo->create();
$all['b'] = $foo->create();
$all['c'] = $foo->create();
$all['d'] = $foo->create();
$all['e'] = $foo->create();
$all['f'] = $foo->create();
```

vs.

``` php
$all['a'] = Something::create($a, $b, $c); // oops, we need $d
$all['b'] = Something::create($a, $b, $c); // oops, we need $d
$all['c'] = Something::create($a, $b, $c); // oops, we need $d
$all['d'] = Something::create($a, $b, $c); // oops, we need $d
$all['e'] = Something::create($a, $b, $c); // oops, we need $d
$all['f'] = Something::create($a, $b, $c); // oops, we need $d
```

---

Also me and @newPOPE are not the only one who dislike this change: https://github.com/nette/sandbox/commit/738738c69d8ee77d770a6966bfa6454197275071

**Comment by dg** [comment]
Use currying.

``` php
$foo = function() use ($a, $b, $c) { return Something::create($a, $b, $c); } // oops, we need $d
$all['a'] = $foo();
```

**Comment by klimesf** [comment]
Begginer friendliness aside:
99% of the time you don't need to change usage of `createRouter()`. You use it only once - in the config - just like you would use the constructor. Furthermore, static functions are evil only if there is a state hidden behind them, which is not the case.

**Comment by newPOPE** [comment]
Easy guys :).

I agree with @dg about static functions and agree with @Majkl578 about that change in sandbox. I just want to know what was the reason to change it to static.

**Comment by dg** [comment]
@newPOPE https://github.com/nette/sandbox/commit/738738c69d8ee77d770a6966bfa6454197275071#commitcomment-8945169

**Comment by newPOPE** [comment]
@dg thanks
