### ISSUE TITLE
Bad static analyze - autoloading standards error

### ISSUE THREAD

**Issue by hamtil** [nette/web-project#24]
I try php static analyze by Phpstan (https://github.com/phpstan/phpstan-nette) and I get trable. It is some bug in web-project or sandbox? (not standardize fs path/namespace)

Step by step:
- composer create-project nette/web-project
- change PHP to 7.2 in composer
- composer require --dev phpstan/phpstan-nette
- create file phpstan.neon (as is write in project) with:
`

includes:
	- vendor/phpstan/phpstan-nette/extension.neon

`
- vendor/bin/phpstan analyse -l 3 -c phpstan.neon app

And get return as:
  Line   presenters/HomepagePresenter.php                                                                                                    
 ------ ------------------------------------------------------------------------------------------------------------------------------------ 
         Class App\Presenters\HomepagePresenter was not found while trying to analyse it - autoloading is probably not configured properly.

I thing than it is bad for beginner with Nette.

**Comment by dg** [comment]
You should properly configure autoloading https://github.com/phpstan/phpstan#autoloading

**Comment by hamtil** [comment]
Yes, you mean point 2 right, after few time (after I realized idea that the problem was not due to my mistake) I get 3 solutions:

1) Manual rewrite dirs:
app to App
presenters to Presenters
router to Router
model to Model (eventualy)
Aplication pull request (https://github.com/nette/web-project/pull/19/commits/437aa39799230255bc85fcf77e840eb9926c7cb1)

2) Add to composer.json:
	"autoload-dev": {
		"psr-4": {
  			"App\\": "app/",
  			"App\\Presenters\\": "app/presenters/",
  			"App\\Router\\": "app/router/",
  			"App\\Model\\": "app/model/"
		}
	}
 
3) Mix it as general standard (see nette library and other) - my favorite:
Manual rewrite dirs:
presenters to Presenters
router to Router
model to Model (eventualy)
Aplication pull request (https://github.com/nette/web-project/pull/19/commits/437aa39799230255bc85fcf77e840eb9926c7cb1)

Add to composer.json:
	"autoload-dev": {
		"psr-4": {
  			"App\\": "app/"
		}
	}



To complement, is there any particular reason for the small first letters of the folders?

Perhaps this will help someone else.

**Comment by dg** [comment]
I think PHPStan should not be installed as you describe, you should install https://github.com/phpstan/phpstan-shim. But I do not have experience with it, maybe I @JanTvrdik or @ondrejmirtes can help.

> To complement, is there any particular reason for the small first letters of the folders?

No, but it is *"impossible"* to change it on Git.

**Comment by ondrejmirtes** [comment]
It's fine to install `phpstan/phpstan` to analyse Nette applications, if Composer allows you to because of version constraints.

This issue was already discussed https://github.com/phpstan/phpstan-nette/issues/37 with the same solution - fix the Composer autoload config.

It might be a mistake here in `nette/web-project` that the Composer autoloader isn't correct, but `nette/web-project` works out of the box because there are multiple autoloaders registered. So it's not anybody's mistake, really.

I think that @dg would accept a PR that improves the Composer `autoload` settings as you @hamtil suggested (have multiple entries for the root namespaces/folders), can you prepare one?

**Comment by hamtil** [comment]
@dg 
https://stackoverflow.com/questions/11183788/in-a-git-repository-how-to-properly-rename-a-directory
`
git mv casesensitive tmp
git mv tmp CaseSensitive
`
I not try really. Would that be a solution for you?


@ondrejmirtes
I do not understand everything so deeply as you.
But I do not think that's the right treatment from my point of view. Poor design of the folder name structure (I do not know if it is wrong, but it fails to check it out) can be confusing for the novices and problem (it killed me for a few hours).
But I understand this (point " 2\. Add to composer.json: " of https://github.com/nette/web-project/issues/24#issuecomment-466624844 ?) can fix the problem (functionality) for PhpStan.
But the problem is not in multiple main directories (they are all in one main dir "app"), but in the wrong filesystem way (CaseSensitive only).
So best point for me for fix and add transparenci benefit for sandbox: " 3\. Mix it as general standard (see nette library and other) - my favorite: " of https://github.com/nette/web-project/issues/24#issuecomment-466624844
The question is whether this is possible and whether it is so right.
I will do PR, but I'm not sure about the right solution.

**Comment by dg** [comment]
To change case is possible, but then hell happens when switching between branches, rebasing, etc. That's why I don't want to do it.

**Comment by hamtil** [comment]
@dg: Ok, I understand. Soo PR with little fix:
https://github.com/nette/web-project/pull/25

**Comment by dg** [comment]
@ondrejmirtes is there way to let PHPStan to use a Robotloader?

**Comment by ondrejmirtes** [comment]
@dg Yes, actually two ways:

1) PHPStan uses RobotLoader internally - when you specify `autoload_directories` (https://github.com/phpstan/phpstan#specify-paths-to-scan), it scans them with RobotLoader, respects ignore lists etc.
2) There's the `-a` CLI option that you can use to load any file, so one possible use is to register your own RobotLoader instance: https://github.com/phpstan/phpstan#autoloading-for-global-installation (and `require` the same file in the app itself probably).

**Comment by dg** [comment]
Well, so this a better solution to this problem, isn't it?

**Comment by ondrejmirtes** [comment]
But with the suggested PR, it will work out of the box. PHPStan can be configured flexibly but novice users do not know about it (and can't bother checking the README :))

**Comment by dg** [comment]
But suggested solution stops working when someone creates a new directory…

**Comment by ondrejmirtes** [comment]
Yeah, if the added directory does not follow PSR-4 (so `App\Domain` isn't under `app/Domain`), then it won't work, but at least the existing directories+files will be discovered by Composer's autoloader :)

**Comment by ondrejmirtes** [comment]
This is no longer a problem as of PHPStan 0.12.26: https://phpstan.org/blog/zero-config-analysis-with-static-reflection

There's a new guide on configuring PHPStan: https://phpstan.org/user-guide/discovering-symbols (but it works out of the box for most projects)
