### ISSUE TITLE
Duplicated key 'search' inside services.neon

### ISSUE THREAD

**Issue by satrapal** [nette/web-project#38]
Version: v3.1.15

### Bug Description
services.neon contains duplicated key 'search' and Nette\Neon\Exception is thrown

### Steps To Reproduce
composer create-project nette/web-project my-project
composer update

### Expected Behavior
Congratulations page

### Possible Solution
Just remove one search key from services.neon and keep that second one

**Comment by dg** [comment]
Fixed
