### ISSUE TITLE
Downloading web-project for new web application

### ISSUE THREAD

**Issue by thepatres** [nette/web-project#9]
Hello, I'd like to ask - you tell on your website, that we should use "composer create-project nette/web-project" for creating new project and also that it is critical that dir /app/ must not be accessible from browser, but in this web-project, there is not any .htaccess to prevent that.

I cloned nette/sandbox and everything is okay, but I am interested in, why it is not in web-project.

Thanks.

**Comment by matej21** [comment]
Correct solution is to set document root to `www` dir

**Comment by thepatres** [comment]
Setting root to www dir will disallow modifing my url to example.com/app/config/... ?

**Comment by milo** [comment]
@patriksimonic Yes. When you point `document_root` into `www`, you cannot step level up. So `app` folder is not accessible by URL.
